<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AdminPIMLeaveTimeRecruitmentMy InfoPerf_cf2048</name>
   <tag></tag>
   <elementGuidId>b85f632e-e326-477a-b104-a3d2ab30e2be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#app</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0064672-1647-4880-8087-38671e5b3eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app</value>
      <webElementGuid>4d610bf9-e796-4ca4-ad7b-bff722e6f06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AdminPIMLeaveTimeRecruitmentMy InfoPerformanceDashboardDirectoryMaintenanceClaimBuzzAdminUser Management Upgrademanda userUser Management Job Organization Qualifications NationalitiesCorporate BrandingMore System UsersUsernameUser Role-- Select --Employee NameStatus-- Select -- Reset  Search  Add  (11) Records FoundUsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActions12345ESS123445 444444DisabledAdminAdminmanda userEnabledChad RodriguezESSJill JonesEnabledenasshamESSenas shamiaEnabledFMLNameESSQwerty LNameEnabledFMLName1ESSFName LNameEnabledHannah HickmanESSMichael FisherEnabledJobinsam@6742ESSJobin SamEnabledMark ThorntonESSRyan ReeseEnabledMichael WintersESSGeorge PotterEnablednetralESSnetra lEnabledOrangeHRM OS 5.8© 2005 - 2026 OrangeHRM, Inc. All rights reserved.</value>
      <webElementGuid>31b101c5-54d8-4a50-ac9c-8e73e39fc218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)</value>
      <webElementGuid>02866d77-5510-4975-b7d1-a941b83cbce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='app']</value>
      <webElementGuid>bab53b8a-cb95-4c66-bffb-e4514b533cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>add4658a-03f6-48c7-b78f-237ff874630a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'app' and (text() = 'AdminPIMLeaveTimeRecruitmentMy InfoPerformanceDashboardDirectoryMaintenanceClaimBuzzAdminUser Management Upgrademanda userUser Management Job Organization Qualifications NationalitiesCorporate BrandingMore System UsersUsernameUser Role-- Select --Employee NameStatus-- Select -- Reset  Search  Add  (11) Records FoundUsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActions12345ESS123445 444444DisabledAdminAdminmanda userEnabledChad RodriguezESSJill JonesEnabledenasshamESSenas shamiaEnabledFMLNameESSQwerty LNameEnabledFMLName1ESSFName LNameEnabledHannah HickmanESSMichael FisherEnabledJobinsam@6742ESSJobin SamEnabledMark ThorntonESSRyan ReeseEnabledMichael WintersESSGeorge PotterEnablednetralESSnetra lEnabledOrangeHRM OS 5.8© 2005 - 2026 OrangeHRM, Inc. All rights reserved.' or . = 'AdminPIMLeaveTimeRecruitmentMy InfoPerformanceDashboardDirectoryMaintenanceClaimBuzzAdminUser Management Upgrademanda userUser Management Job Organization Qualifications NationalitiesCorporate BrandingMore System UsersUsernameUser Role-- Select --Employee NameStatus-- Select -- Reset  Search  Add  (11) Records FoundUsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActions12345ESS123445 444444DisabledAdminAdminmanda userEnabledChad RodriguezESSJill JonesEnabledenasshamESSenas shamiaEnabledFMLNameESSQwerty LNameEnabledFMLName1ESSFName LNameEnabledHannah HickmanESSMichael FisherEnabledJobinsam@6742ESSJobin SamEnabledMark ThorntonESSRyan ReeseEnabledMichael WintersESSGeorge PotterEnablednetralESSnetra lEnabledOrangeHRM OS 5.8© 2005 - 2026 OrangeHRM, Inc. All rights reserved.')]</value>
      <webElementGuid>188886e7-ca39-4d12-8ef8-4886b47134bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
